{{- if $.Values.configmaps }}
{{- range $key, $value := $.Values.configmaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $key }}
  namespace: {{ $.Values.namespace }}
  labels:
    environment: {{ $.Values.environment }}
  annotations:
    reloader.stakater.com/match: "true"
data: {{ toYaml $value | nindent 2 }}
{{- end }}
{{- end }}