{{- $labels := dict "app" $.Values.name "environment" $.Values.environment }}

{{- if $.Values.image }}
---
apiVersion: apps/v1
kind: {{ $.Values.kind | default "Deployment" }}
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: {{ $.Values.name }}
  namespace: {{ $.Values.namespace }}
  labels: {{ toYaml (mergeOverwrite ($.Values.labels | default dict) $labels) | nindent 4 }}
spec:
  replicas: {{ $.Values.replicas | default 1 }}
  revisionHistoryLimit: 3
{{- if or (not $.Values.kind) (eq $.Values.kind "Deployment") }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ $.Values.maxSurge | default 1 }}
      maxUnavailable: {{ $.Values.maxUnavailable | default 0 }}
{{- end }}
  selector:
    matchLabels: {{ toYaml $labels | nindent 6 }}
  template:
    metadata:
      labels: {{ toYaml $labels | nindent 8 }}
{{- $affinity := $.Values.app_affinity }}
{{- with index $affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution 0 }}
{{- $_ := set .podAffinityTerm.labelSelector "matchLabels" (dict "app" $.Values.name) }}
{{- end }}
{{- $spec := dict }}
{{- $_ := set $spec "affinity" $affinity }}
{{- $_ := set $spec "nodeSelector" $.Values.app_selector }}
{{- $_ := set $spec "serviceAccountName" (print "sa-" $.Values.namespace) }}
{{- $container := dict }}
{{- range $key, $value := $.Values }}
{{- if has $key $.Values.container_keys }}
{{- $_ := set $container $key $value }}
{{- else if has $key $.Values.spec_keys }}
{{- $_ := set $spec $key $value }}
{{- end }}
{{- end }}
{{- $_ := set $spec "containers" (list $container) }}
    spec: {{ toYaml $spec | nindent 6 }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds | default 30 }}
{{- end }}