{{- $labels := dict "app" $.Values.name "environment" $.Values.environment }}

{{- if $.Values.gateway_routes }}
{{- range $host, $value := $.Values.gateway_routes }}
{{- range $index, $services := chunk 14 (keys $value) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $host }}-{{ $index }}
  namespace: {{ $.Values.namespace }}
spec:
  parentRefs:
  - name: gateway
    namespace: gateway
  hostnames:
  - {{ $host }}
  rules:
{{- range $svc := $services }}
{{- range $item := chunk 8 (get $value $svc) }}
  - backendRefs:
    - name: {{ (split "_" $svc)._0 }}
      port: {{ (split "_" $svc)._1 }}
      kind: Service
    matches:
{{- range $path := $item }}
    - path:
        type: PathPrefix
        value: {{ $path }}
{{- end }}
    timeouts:
      backendRequest: 60s
      request: 60s
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}