{{- $labels := dict "app" $.Values.name "environment" $.Values.environment }}

{{- if or $.Values.hpa $.Values.hpa_spec }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Values.name }}
  namespace: {{ $.Values.namespace }}
  labels: {{ toYaml $labels | nindent 4 }}
{{- if $.Values.hpa }}
spec:
  minReplicas: {{ $.Values.hpa.minReplicas }}
  maxReplicas: {{ $.Values.hpa.maxReplicas }}
  behavior:
    scaleDown:
      policies:
        - type: Percent
          value: 5
          periodSeconds: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ $.Values.kind }}
    name: {{ $.Values.name }}
  metrics:
{{- if $.Values.resources.requests.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.hpa.cpuPct | default 100 }}
{{- end }}
{{- if $.Values.resources.requests.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $.Values.hpa.memPct | default 100 }}
{{- end }}
{{- else if $.Values.hpa_spec }}
spec: {{ toYaml $.Values.hpa_spec | nindent 2 }}
{{- end }}
{{- end }}