{{- range $key, $value := $.Values }}
{{- if contains "routes_" $key }}
{{- $host := (split "_" $key)._1 }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ print $host "-" $.Values.name }}
  namespace: {{ $.Values.namespace }}
spec:
  parentRefs:
  - name: gateway
    namespace: gateway
  hostnames:
{{- range $dmn := $.Values.domains | sortAlpha }}
  - {{ print $host "." $dmn }}
{{- end }}
  rules:
{{- $routes := chunk 7 $value }}
{{- range $item := $routes }}
  - backendRefs:
    - kind: Service
      name: {{ $.Values.name }}
      port: {{ $.Values.gw_port | default 80 }}
    matches:
{{- range $route := $item | sortAlpha }}
    - path:
        type: PathPrefix
        value: {{ $route }}
{{- end }}
    timeouts:
      backendRequest: 60s
      request: 60s
{{- end }}
{{- end }}
{{- end }}