{{- $routes := .Values.routes }}
{{- range $host, $services := $routes }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Values.name }}-{{ $host | replace "." "-" }}
  namespace: {{ $.Values.namespace }}
spec:
  hostnames:
    - {{ $host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: gateway
  rules:
    {{- range $serviceName, $service := $services }}
    {{- $paths := $service.paths }}
    {{- $numPaths := (len $paths) }}
    {{- $batches := (div (add $numPaths 6) 7) }}
    {{- range $i := until ($batches| int) }}
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ $serviceName }}
          port: {{ $service.port | default 80}}
      matches:
        {{- $start := mul $i 7 }}
        {{- $end := min (add $start 7) $numPaths }}
        {{- range $index, $path := (slice $paths $start $end) }}
        {{- if not $path.features }}
          - path:
              type: PathPrefix
              value: {{ $path.name }}
            {{- end }}
        {{- end }}
      timeouts:
        backendRequest: 60s
        request: 60s
    {{- end }}
  {{- end }}
{{- end }}
---
{{- range $host, $services := $routes }}
{{- range $serviceName, $service := $services }}
{{- if and $service.features.retries $service.features.retries.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ $.Values.name }}-{{ $serviceName }}-{{ $host | replace "." "-" }}
  namespace: {{ $.Values.namespace }}
spec:
  retry:
    numRetries: {{ $service.features.retries.configuration.numRetries | default 3 }}
    perRetry:
      timeout: {{ $service.features.retries.configuration.perRetry.timeout | default 3s }}
      backOff:
        baseInterval: {{ $service.features.retries.configuration.perRetry.backOff.baseInterval | default 1s }}
        maxInterval: {{ $service.features.retries.configuration.perRetry.backOff.maxInterval | default 3s }}
    retryOn:
      triggers:
         {{- $defaultTriggers := (list "gateway-error") }}
         {{- range $trigger := (or $service.features.retries.configuration.retryOn.triggers $defaultTriggers) }}
         - {{ $trigger }}
         {{- end }} 
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ $.Values.name }}-{{ $host | replace "." "-" }}
    namespace: {{ $.Values.namespace }}
{{- end }}
{{- end }}
{{- end }}
