{{- $routes := .Values.routes }}
{{- range $host, $services := $routes }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Values.name }}-{{ $host | replace "." "-" }}
  namespace: {{ $.Values.namespace }}
spec:
  hostnames:
    - {{ $host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: gateway
  rules:
    {{- range $serviceName, $service := $services }}
    {{- $paths := $service.paths }}
    {{- $numPaths := (len $paths) }}
    {{- $batches := (div $numPaths 7) }}
    {{- range $i := until ($batches| int) }}
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ $serviceName }}
          port: {{ $service.port }}
      matches:
        {{- $start := mul $i 7 }}
        {{- $end := min (add $start 7) $numPaths }}
        {{- range $index, $path := (slice $paths $start $end) }}
        - path:
            type: PathPrefix
            value: {{ $path.name }}
            {{- if $path.gzip }}
            gzip: true
            {{- end }}
        {{- end }}
      timeouts:
        backendRequest: 60s
        request: 60s
    {{- end }}
  {{- end }}
{{- end }}
