{{- $labels := dict "app" $.Values.name "environment" $.Values.environment }}

{{- if $.Values.service_ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.name }}
  namespace: {{ $.Values.namespace }}
  labels: {{ toYaml (mergeOverwrite (dict "monitoring" "true") $labels $.Values.labels) | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ toYaml $labels | nindent 4 }}
  ports: {{ toYaml $.Values.service_ports | nindent 2 }}
{{- end }}