ports:
- containerPort: 8080

spec_keys:
- volumes
- affinity
- tolerations
- nodeSelector
- securityContext
- serviceAccountName

container_keys:
- name
- image
- env
- envFrom
- ports
- command
- args
- resources
- volumeMounts
- livenessProbe
- readinessProbe

app_selector:
  role: app

app_affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app: app
        topologyKey: "kubernetes.io/hostname"


service_ports:
- name: http
  port: 80
  protocol: TCP
  targetPort: 8080
- name: metrics
  port: 9090
  protocol: TCP
  targetPort: 9090